const SAT_QUESTIONS = {
  module1: [
    {
      id: "m1_q1",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "medium",
      stimulus: "",
      question: "If 3x + 7 = 22, what is the value of x?",
      choices: { A: "3", B: "5", C: "7", D: "9" },
      correct_answer: "B",
      explanation: "Subtract 7 from both sides: 3x = 15, then divide by 3: x = 5."
    },
    {
      id: "m1_q2",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "medium",
      stimulus: "",
      question: "A line passes through the points (2, 5) and (4, 11). What is the slope of the line?",
      choices: { A: "2", B: "3", C: "4", D: "6" },
      correct_answer: "B",
      explanation: "Slope = (11 - 5) / (4 - 2) = 6 / 2 = 3."
    },
    {
      id: "m1_q3",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "medium",
      stimulus: "",
      question: "If 2x + 3y = 12 and x - y = 1, what is the value of x + y?",
      choices: { A: "3", B: "4", C: "5", D: "6" },
      correct_answer: "C",
      explanation: "Solve the system: x = y + 1, so 2(y + 1) + 3y = 12, 2y + 2 + 3y = 12, 5y = 10, y = 2. Then x = 3. So x + y = 5."
    },
    {
      id: "m1_q4",
      type: "free_response",
      domain: "Algebra",
      difficulty: "medium",
      stimulus: "",
      question: "If 4(x - 3) = 2x + 8, what is the value of x?",
      choices: null,
      correct_answer: "10",
      explanation: "4x - 12 = 2x + 8, 4x - 2x = 8 + 12, 2x = 20, x = 10."
    },
    {
      id: "m1_q5",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "medium",
      stimulus: "",
      question: "What is the sum of the solutions to the equation x² - 7x + 12 = 0?",
      choices: { A: "3", B: "4", C: "7", D: "12" },
      correct_answer: "C",
      explanation: "The sum of solutions of ax² + bx + c = 0 is -b/a = -(-7)/1 = 7."
    },
    {
      id: "m1_q6",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "medium",
      stimulus: "",
      question: "If f(x) = 2x² - 3x + 1, what is f(2)?",
      choices: { A: "1", B: "3", C: "5", D: "7" },
      correct_answer: "B",
      explanation: "f(2) = 2(4) - 3(2) + 1 = 8 - 6 + 1 = 3."
    },
    {
      id: "m1_q7",
      type: "free_response",
      domain: "Advanced Math",
      difficulty: "medium",
      stimulus: "",
      question: "If 3ˣ = 81, what is the value of x?",
      choices: null,
      correct_answer: "4",
      explanation: "81 = 3⁴, so 3ˣ = 3⁴, therefore x = 4."
    },
    {
      id: "m1_q8",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "medium",
      stimulus: "",
      question: "What is the value of √(50) + √(18) expressed in simplest radical form?",
      choices: { A: "2√17", B: "5√2 + 3√2", C: "8√2", D: "√68" },
      correct_answer: "C",
      explanation: "√50 = 5√2, √18 = 3√2, so sum = 8√2."
    },
    {
      id: "m1_q9",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "A survey of 200 students asked about their favorite subject. The results are shown in the table below.<br><br>Subject | Number of Students<br>Math | 50<br>Science | 40<br>English | 60<br>History | 30<br>Other | 20",
      question: "What percentage of students chose Math as their favorite subject?",
      choices: { A: "20%", B: "25%", C: "30%", D: "50%" },
      correct_answer: "B",
      explanation: "50 out of 200 students chose Math. 50/200 = 0.25 = 25%."
    },
    {
      id: "m1_q10",
      type: "free_response",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "",
      question: "A recipe calls for 3 cups of flour for every 2 cups of sugar. If you use 9 cups of flour, how many cups of sugar are needed?",
      choices: null,
      correct_answer: "6",
      explanation: "The ratio is 3:2 flour to sugar. 9/3 = 3, so multiply sugar by 3: 2 × 3 = 6."
    },
    {
      id: "m1_q11",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "",
      question: "A store is having a 30% off sale on all items. If a shirt originally costs $45, what is the sale price?",
      choices: { A: "$13.50", B: "$27.00", C: "$31.50", D: "$35.00" },
      correct_answer: "C",
      explanation: "30% of $45 = $13.50 discount. Sale price = $45 - $13.50 = $31.50."
    },
    {
      id: "m1_q12",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "The line graph below shows the number of books sold at a store over 5 months.<br><br>Month | Books Sold<br>Jan | 120<br>Feb | 150<br>Mar | 110<br>Apr | 180<br>May | 200",
      question: "What is the median number of books sold per month?",
      choices: { A: "120", B: "150", C: "152", D: "160" },
      correct_answer: "B",
      explanation: "Ordered: 110, 120, 150, 180, 200. The median is the middle value: 150."
    },
    {
      id: "m1_q13",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "medium",
      stimulus: "",
      question: "A rectangle has a length of 12 cm and a width of 5 cm. What is the area of the rectangle?",
      choices: { A: "17 cm²", B: "34 cm²", C: "60 cm²", D: "144 cm²" },
      correct_answer: "C",
      explanation: "Area of a rectangle = length × width = 12 × 5 = 60 cm²."
    },
    {
      id: "m1_q14",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "medium",
      stimulus: "",
      question: "In a right triangle, the legs have lengths 6 and 8. What is the length of the hypotenuse?",
      choices: { A: "9", B: "10", C: "12", D: "14" },
      correct_answer: "B",
      explanation: "By the Pythagorean theorem: c² = 6² + 8² = 36 + 64 = 100, so c = 10."
    },
    {
      id: "m1_q15",
      type: "free_response",
      domain: "Geometry & Trigonometry",
      difficulty: "medium",
      stimulus: "",
      question: "A circle has a radius of 7. What is its circumference? (Use π = 22/7.)",
      choices: null,
      correct_answer: "44",
      explanation: "Circumference = 2πr = 2 × 22/7 × 7 = 44."
    },
    {
      id: "m1_q16",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "medium",
      stimulus: "",
      question: "If 2x - 5 ≤ 7, what is the greatest integer value of x that satisfies the inequality?",
      choices: { A: "5", B: "6", C: "7", D: "8" },
      correct_answer: "B",
      explanation: "2x - 5 ≤ 7, 2x ≤ 12, x ≤ 6. The greatest integer satisfying x ≤ 6 is 6."
    },
    {
      id: "m1_q17",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "medium",
      stimulus: "",
      question: "The function f is defined by f(x) = 3(2)ˣ. What is the value of f(3)?",
      choices: { A: "18", B: "24", C: "48", D: "216" },
      correct_answer: "B",
      explanation: "f(3) = 3(2)³ = 3(8) = 24."
    },
    {
      id: "m1_q18",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "",
      question: "If a car travels at a constant speed of 65 miles per hour, how many miles will it travel in 3.5 hours?",
      choices: { A: "195.0", B: "210.5", C: "227.5", D: "240.0" },
      correct_answer: "C",
      explanation: "Distance = rate × time = 65 × 3.5 = 227.5 miles."
    },
    {
      id: "m1_q19",
      type: "free_response",
      domain: "Advanced Math",
      difficulty: "medium",
      stimulus: "",
      question: "If (x + 3)(x - 2) = x² + ax - 6, what is the value of a?",
      choices: null,
      correct_answer: "1",
      explanation: "(x + 3)(x - 2) = x² + x - 6, so a = 1."
    },
    {
      id: "m1_q20",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "medium",
      stimulus: "",
      question: "In triangle ABC, angle A = 50° and angle B = 70°. What is the measure of angle C?",
      choices: { A: "40°", B: "50°", C: "60°", D: "70°" },
      correct_answer: "C",
      explanation: "Sum of angles in a triangle = 180°. So C = 180 - 50 - 70 = 60°."
    },
    {
      id: "m1_q21",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "",
      question: "A bag contains 4 red marbles, 6 blue marbles, and 10 green marbles. If one marble is randomly selected, what is the probability that it is blue?",
      choices: { A: "0.15", B: "0.20", C: "0.30", D: "0.40" },
      correct_answer: "C",
      explanation: "Total marbles = 4 + 6 + 10 = 20. P(blue) = 6/20 = 3/10 = 0.30."
    },
    {
      id: "m1_q22",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "medium",
      stimulus: "",
      question: "The cost of renting a bike is $8 per hour plus a $5 flat fee. Which equation represents the total cost C for renting the bike for h hours?",
      choices: { A: "C = 8h + 5", B: "C = 5h + 8", C: "C = 13h", D: "C = 8h - 5" },
      correct_answer: "A",
      explanation: "The $5 flat fee is a constant, and $8 per hour means $8h. So C = 8h + 5."
    }
  ],
  module2_hard: [
    {
      id: "m2h_q1",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "hard",
      stimulus: "",
      question: "If 3x + 2y = 12 and 5x - 2y = 4, what is the value of x + y?",
      choices: { A: "2", B: "3", C: "4", D: "5" },
      correct_answer: "D",
      explanation: "Add the two equations: 8x = 16, so x = 2. Substituting: 3(2) + 2y = 12, 6 + 2y = 12, 2y = 6, y = 3. So x + y = 5."
    },
    {
      id: "m2h_q2",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "If f(x) = x² - 4x + 7, what is the minimum value of f(x)?",
      choices: { A: "2", B: "3", C: "4", D: "7" },
      correct_answer: "B",
      explanation: "The vertex occurs at x = -b/(2a) = 4/2 = 2. f(2) = 4 - 8 + 7 = 3. Since a = 1 > 0, this is the minimum."
    },
    {
      id: "m2h_q3",
      type: "free_response",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "If 2x² - 5x - 12 = 0, what is the positive value of x?",
      choices: null,
      correct_answer: "4",
      explanation: "Factor: (2x + 3)(x - 4) = 0. So x = -3/2 or x = 4. The positive solution is 4."
    },
    {
      id: "m2h_q4",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "hard",
      stimulus: "",
      question: "The population of a town increases by 8% each year. If the current population is 5,000, which expression gives the population after t years?",
      choices: { A: "5000(0.92)ᵗ", B: "5000(1.08)ᵗ", C: "5000 + 400t", D: "5000(8)ᵗ" },
      correct_answer: "B",
      explanation: "An 8% increase means multiplying by 1.08 each year. So population = 5000(1.08)ᵗ."
    },
    {
      id: "m2h_q5",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "hard",
      stimulus: "",
      question: "A right triangle has an angle of 30° and an adjacent side of length 6. What is the length of the hypotenuse?",
      choices: { A: "3√3", B: "4√3", C: "6√3", D: "12" },
      correct_answer: "B",
      explanation: "cos(30°) = adjacent/hypotenuse = 6/h. So h = 6/cos(30°) = 6/(√3/2) = 12/√3 = 4√3."
    },
    {
      id: "m2h_q6",
      type: "free_response",
      domain: "Problem Solving & Data Analysis",
      difficulty: "hard",
      stimulus: "The table below shows the number of points scored by a basketball team in 10 games.<br><br>Game | Points<br>1 | 78<br>2 | 82<br>3 | 91<br>4 | 67<br>5 | 85<br>6 | 73<br>7 | 88<br>8 | 79<br>9 | 94<br>10 | 83",
      question: "What is the mean of the data values, rounded to the nearest whole number?",
      choices: null,
      correct_answer: "82",
      explanation: "Sum = 78 + 82 + 91 + 67 + 85 + 73 + 88 + 79 + 94 + 83 = 820. Mean = 820/10 = 82."
    },
    {
      id: "m2h_q7",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "hard",
      stimulus: "",
      question: "If |2x - 5| = 11, what are the possible values of x?",
      choices: { A: "3 and -8", B: "8 and -3", C: "8 and 3", D: "-8 and -3" },
      correct_answer: "B",
      explanation: "2x - 5 = 11 gives 2x = 16, x = 8. 2x - 5 = -11 gives 2x = -6, x = -3."
    },
    {
      id: "m2h_q8",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "If (x - 2) is a factor of x³ + kx² - 4x - 12, what is the value of k?",
      choices: { A: "1", B: "2", C: "3", D: "4" },
      correct_answer: "C",
      explanation: "If (x - 2) is a factor, then f(2) = 0. f(2) = 8 + 4k - 8 - 12 = 4k - 12 = 0, so k = 3."
    },
    {
      id: "m2h_q9",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "hard",
      stimulus: "",
      question: "A data set has a mean of 50 and a standard deviation of 5. Assuming a normal distribution, approximately what percentage of values lie between 40 and 60?",
      choices: { A: "68%", B: "75%", C: "95%", D: "99.7%" },
      correct_answer: "C",
      explanation: "40 is 2 standard deviations below the mean and 60 is 2 above. In a normal distribution, about 95% of values lie within 2 standard deviations of the mean."
    },
    {
      id: "m2h_q10",
      type: "free_response",
      domain: "Geometry & Trigonometry",
      difficulty: "hard",
      stimulus: "",
      question: "A cylinder has a height of 10 cm and a base radius of 3 cm. What is its volume in cubic cm? (Use π = 3.14.)",
      choices: null,
      correct_answer: "282.6",
      explanation: "Volume = πr²h = 3.14 × 9 × 10 = 282.6."
    },
    {
      id: "m2h_q11",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "If 2^(x+1) = 32, what is the value of x?",
      choices: { A: "2", B: "3", C: "4", D: "5" },
      correct_answer: "C",
      explanation: "2^(x+1) = 32 = 2⁵, so x + 1 = 5, x = 4."
    },
    {
      id: "m2h_q12",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "hard",
      stimulus: "",
      question: "If (ax + b)(cx + d) = 6x² + 11x - 10 for all x, and a, b, c, d are integers with a > 0, what is the value of a + c?",
      choices: { A: "5", B: "6", C: "7", D: "11" },
      correct_answer: "A",
      explanation: "Factor 6x² + 11x - 10 = (2x + 5)(3x - 2). So (a, c) = (2, 3) or (3, 2). Either way, a + c = 5."
    },
    {
      id: "m2h_q13",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "hard",
      stimulus: "",
      question: "In the xy-plane, a circle has center (3, -2) and radius 5. Which of the following is an equation of the circle?",
      choices: { A: "(x - 3)² + (y + 2)² = 5", B: "(x - 3)² + (y + 2)² = 25", C: "(x + 3)² + (y - 2)² = 25", D: "(x + 3)² + (y - 2)² = 5" },
      correct_answer: "B",
      explanation: "The equation of a circle with center (h, k) and radius r is (x - h)² + (y - k)² = r². So (x - 3)² + (y + 2)² = 25."
    },
    {
      id: "m2h_q14",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "hard",
      stimulus: "The scatterplot below shows the relationship between hours studied and test scores for 12 students.<br><br>Hours Studied: 1, 1.5, 2, 2, 2.5, 3, 3, 3.5, 4, 4, 4.5, 5<br>Test Scores: 55, 60, 62, 65, 68, 70, 75, 78, 80, 82, 85, 90",
      question: "The line of best fit for the data is approximately y = 8x + 50. Based on this model, what score would a student who studies for 6 hours be predicted to receive?",
      choices: { A: "88", B: "92", C: "96", D: "98" },
      correct_answer: "D",
      explanation: "y = 8(6) + 50 = 48 + 50 = 98."
    },
    {
      id: "m2h_q15",
      type: "free_response",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "If 3√(x + 4) = 15, what is the value of x?",
      choices: null,
      correct_answer: "21",
      explanation: "3√(x + 4) = 15, √(x + 4) = 5, x + 4 = 25, x = 21."
    },
    {
      id: "m2h_q16",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "hard",
      stimulus: "",
      question: "A car rental company charges a base fee of $25 plus $0.30 per mile driven. Which inequality represents the maximum number of miles m a customer can drive if they want to spend at most $70?",
      choices: { A: "25m + 0.30 ≤ 70", B: "0.30m + 25 ≤ 70", C: "0.30m + 25 ≥ 70", D: "25 + 0.30m ≥ 70" },
      correct_answer: "B",
      explanation: "Total cost = 0.30m + 25. At most $70 means total ≤ 70: 0.30m + 25 ≤ 70."
    },
    {
      id: "m2h_q17",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "hard",
      stimulus: "",
      question: "What is sin(60°)?",
      choices: { A: "0", B: "1/2", C: "√3/2", D: "1" },
      correct_answer: "C",
      explanation: "sin(60°) = √3/2."
    },
    {
      id: "m2h_q18",
      type: "free_response",
      domain: "Problem Solving & Data Analysis",
      difficulty: "hard",
      stimulus: "",
      question: "If the probability of an event is 0.25 and the event is attempted 120 times, what is the expected number of successes?",
      choices: null,
      correct_answer: "30",
      explanation: "Expected number = probability × number of trials = 0.25 × 120 = 30."
    },
    {
      id: "m2h_q19",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "The expression (x² + 3x - 10)/(x - 2) simplifies to which of the following for x ≠ 2?",
      choices: { A: "x - 5", B: "x + 5", C: "x - 3", D: "x + 3" },
      correct_answer: "B",
      explanation: "x² + 3x - 10 = (x + 5)(x - 2). So (x² + 3x - 10)/(x - 2) = x + 5 for x ≠ 2."
    },
    {
      id: "m2h_q20",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "hard",
      stimulus: "",
      question: "A sphere has a volume of 288π cubic units. What is its radius?",
      choices: { A: "3", B: "4", C: "5", D: "6" },
      correct_answer: "D",
      explanation: "Volume of sphere = (4/3)πr³ = 288π. So (4/3)r³ = 288, r³ = 216, r = 6."
    },
    {
      id: "m2h_q21",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "hard",
      stimulus: "",
      question: "If f(x) = 3x - 2 and g(x) = 2x + 5, what is f(g(1))?",
      choices: { A: "13", B: "16", C: "19", D: "21" },
      correct_answer: "C",
      explanation: "g(1) = 2(1) + 5 = 7. f(7) = 3(7) - 2 = 21 - 2 = 19."
    },
    {
      id: "m2h_q22",
      type: "free_response",
      domain: "Problem Solving & Data Analysis",
      difficulty: "hard",
      stimulus: "The box plot below shows the distribution of test scores for a class of 30 students.<br><br>Minimum: 45, Q1: 62, Median: 74, Q3: 85, Maximum: 98",
      question: "What is the interquartile range (IQR) of the test scores?",
      choices: null,
      correct_answer: "23",
      explanation: "IQR = Q3 - Q1 = 85 - 62 = 23."
    }
  ],
  module2_easy: [
    {
      id: "m2e_q1",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "easy",
      stimulus: "",
      question: "If x + 7 = 15, what is the value of x?",
      choices: { A: "6", B: "7", C: "8", D: "9" },
      correct_answer: "C",
      explanation: "x + 7 = 15, subtract 7 from both sides: x = 8."
    },
    {
      id: "m2e_q2",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "easy",
      stimulus: "",
      question: "What is the slope of the line y = 3x - 5?",
      choices: { A: "-5", B: "3", C: "5", D: "-3" },
      correct_answer: "B",
      explanation: "In y = mx + b, the slope m = 3."
    },
    {
      id: "m2e_q3",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "easy",
      stimulus: "",
      question: "What is the value of 2³?",
      choices: { A: "4", B: "6", C: "8", D: "9" },
      correct_answer: "C",
      explanation: "2³ = 2 × 2 × 2 = 8."
    },
    {
      id: "m2e_q4",
      type: "free_response",
      domain: "Algebra",
      difficulty: "easy",
      stimulus: "",
      question: "If 2x = 14, what is the value of x?",
      choices: null,
      correct_answer: "7",
      explanation: "2x = 14, divide both sides by 2: x = 7."
    },
    {
      id: "m2e_q5",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "easy",
      stimulus: "",
      question: "A pizza is cut into 8 equal slices. If 3 slices are eaten, what fraction of the pizza remains?",
      choices: { A: "3/8", B: "5/8", C: "3/5", D: "5/3" },
      correct_answer: "B",
      explanation: "8 slices total, 3 eaten, so 5 remain. Fraction = 5/8."
    },
    {
      id: "m2e_q6",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "easy",
      stimulus: "",
      question: "What is the area of a square with side length 4?",
      choices: { A: "8", B: "12", C: "16", D: "20" },
      correct_answer: "C",
      explanation: "Area of a square = side² = 4² = 16."
    },
    {
      id: "m2e_q7",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "easy",
      stimulus: "",
      question: "What is 50% of 200?",
      choices: { A: "50", B: "75", C: "100", D: "150" },
      correct_answer: "C",
      explanation: "50% of 200 = 0.50 × 200 = 100."
    },
    {
      id: "m2e_q8",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "easy",
      stimulus: "",
      question: "If f(x) = 2x + 3, what is f(4)?",
      choices: { A: "8", B: "9", C: "10", D: "11" },
      correct_answer: "D",
      explanation: "f(4) = 2(4) + 3 = 8 + 3 = 11."
    },
    {
      id: "m2e_q9",
      type: "free_response",
      domain: "Problem Solving & Data Analysis",
      difficulty: "easy",
      stimulus: "",
      question: "A bag contains 10 marbles: 4 red and 6 blue. What is the probability of randomly drawing a red marble?",
      choices: null,
      correct_answer: "0.4",
      explanation: "P(red) = 4/10 = 0.4."
    },
    {
      id: "m2e_q10",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "easy",
      stimulus: "",
      question: "A triangle has a base of 6 and a height of 4. What is its area?",
      choices: { A: "10", B: "12", C: "20", D: "24" },
      correct_answer: "B",
      explanation: "Area of triangle = (1/2) × base × height = (1/2) × 6 × 4 = 12."
    },
    {
      id: "m2e_q11",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "easy",
      stimulus: "",
      question: "If 3(x - 2) = 9, what is the value of x?",
      choices: { A: "3", B: "4", C: "5", D: "6" },
      correct_answer: "C",
      explanation: "3(x - 2) = 9, x - 2 = 3, x = 5."
    },
    {
      id: "m2e_q12",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "easy",
      stimulus: "",
      question: "What is the product of (x + 2)(x + 3)?",
      choices: { A: "x² + 5x + 6", B: "x² + 5x + 5", C: "x² + 6x + 6", D: "x² + 6x + 5" },
      correct_answer: "A",
      explanation: "(x + 2)(x + 3) = x² + 3x + 2x + 6 = x² + 5x + 6."
    },
    {
      id: "m2e_q13",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "easy",
      stimulus: "",
      question: "If 3 apples cost $1.50, what is the cost of 1 apple?",
      choices: { A: "$0.30", B: "$0.50", C: "$0.75", D: "$1.00" },
      correct_answer: "B",
      explanation: "$1.50 ÷ 3 = $0.50 per apple."
    },
    {
      id: "m2e_q14",
      type: "free_response",
      domain: "Geometry & Trigonometry",
      difficulty: "easy",
      stimulus: "",
      question: "What is the perimeter of a rectangle with length 7 and width 3?",
      choices: null,
      correct_answer: "20",
      explanation: "Perimeter = 2(l + w) = 2(7 + 3) = 2(10) = 20."
    },
    {
      id: "m2e_q15",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "easy",
      stimulus: "",
      question: "Which of the following is a solution to the inequality x + 3 > 8?",
      choices: { A: "3", B: "4", C: "5", D: "6" },
      correct_answer: "D",
      explanation: "x + 3 > 8, x > 5. Only 6 satisfies x > 5."
    },
    {
      id: "m2e_q16",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "easy",
      stimulus: "",
      question: "What is the value of √36 + √9?",
      choices: { A: "6", B: "9", C: "12", D: "15" },
      correct_answer: "B",
      explanation: "√36 = 6, √9 = 3, 6 + 3 = 9."
    },
    {
      id: "m2e_q17",
      type: "free_response",
      domain: "Advanced Math",
      difficulty: "easy",
      stimulus: "",
      question: "If x² = 49, what is the positive value of x?",
      choices: null,
      correct_answer: "7",
      explanation: "x² = 49, x = 7 or x = -7. The positive value is 7."
    },
    {
      id: "m2e_q18",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "easy",
      stimulus: "The bar graph below shows the number of books read by students in a month.<br><br>Student | Books Read<br>Alice | 5<br>Bob | 3<br>Carol | 7<br>Dave | 4",
      question: "How many total books did the students read?",
      choices: { A: "15", B: "17", C: "19", D: "21" },
      correct_answer: "C",
      explanation: "Total = 5 + 3 + 7 + 4 = 19."
    },
    {
      id: "m2e_q19",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "easy",
      stimulus: "",
      question: "A circle has a radius of 5. What is its area? (Use π = 3.14.)",
      choices: { A: "31.4", B: "62.8", C: "78.5", D: "157" },
      correct_answer: "C",
      explanation: "Area = πr² = 3.14 × 25 = 78.5."
    },
    {
      id: "m2e_q20",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "easy",
      stimulus: "",
      question: "A train travels 240 miles in 4 hours. What is its average speed in miles per hour?",
      choices: { A: "40", B: "50", C: "60", D: "80" },
      correct_answer: "C",
      explanation: "Speed = distance/time = 240/4 = 60 mph."
    },
    {
      id: "m2e_q21",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "easy",
      stimulus: "",
      question: "If x + y = 10 and y = 3, what is the value of x?",
      choices: { A: "3", B: "5", C: "7", D: "10" },
      correct_answer: "C",
      explanation: "x + 3 = 10, x = 7."
    },
    {
      id: "m2e_q22",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "easy",
      stimulus: "",
      question: "What is the value of (½)³?",
      choices: { A: "1/8", B: "1/6", C: "1/3", D: "1/2" },
      correct_answer: "A",
      explanation: "(½)³ = 1/2 × 1/2 × 1/2 = 1/8."
    }
  ],
  quick_test: [
    {
      id: "qt_q1",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "medium",
      stimulus: "",
      question: "If 5x - 3 = 3x + 9, what is the value of x?",
      choices: { A: "3", B: "4", C: "6", D: "12" },
      correct_answer: "C",
      explanation: "5x - 3 = 3x + 9, 5x - 3x = 9 + 3, 2x = 12, x = 6."
    },
    {
      id: "qt_q2",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "medium",
      stimulus: "",
      question: "If x² - 9 = 0, what are the solutions?",
      choices: { A: "3 only", B: "-3 only", C: "3 and -3", D: "0 and 9" },
      correct_answer: "C",
      explanation: "x² - 9 = (x - 3)(x + 3) = 0, so x = 3 or x = -3."
    },
    {
      id: "qt_q3",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "medium",
      stimulus: "",
      question: "What is the volume of a rectangular prism with length 5, width 4, and height 3?",
      choices: { A: "20", B: "30", C: "40", D: "60" },
      correct_answer: "D",
      explanation: "Volume = l × w × h = 5 × 4 × 3 = 60."
    },
    {
      id: "qt_q4",
      type: "free_response",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "",
      question: "A store sells a item for $24 after a 20% discount. What was the original price?",
      choices: null,
      correct_answer: "30",
      explanation: "Let p be the original price. After 20% discount, price = 0.80p = 24, so p = 24/0.80 = 30."
    },
    {
      id: "qt_q5",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "If 3x² - 12x + 9 = 0, what is the sum of the solutions?",
      choices: { A: "2", B: "3", C: "4", D: "6" },
      correct_answer: "C",
      explanation: "For ax² + bx + c = 0, sum of solutions = -b/a = -(-12)/3 = 12/3 = 4."
    },
    {
      id: "qt_q6",
      type: "multiple_choice",
      domain: "Geometry & Trigonometry",
      difficulty: "hard",
      stimulus: "",
      question: "A cone has a base radius of 3 and a height of 7. What is its volume?",
      choices: { A: "21π", B: "28π", C: "42π", D: "63π" },
      correct_answer: "A",
      explanation: "Volume of cone = (1/3)πr²h = (1/3)π(9)(7) = 21π."
    },
    {
      id: "qt_q7",
      type: "free_response",
      domain: "Algebra",
      difficulty: "hard",
      stimulus: "",
      question: "If 2^(2x) = 16, what is the value of x?",
      choices: null,
      correct_answer: "2",
      explanation: "2^(2x) = 16 = 2⁴, so 2x = 4, x = 2."
    },
    {
      id: "qt_q8",
      type: "multiple_choice",
      domain: "Problem Solving & Data Analysis",
      difficulty: "medium",
      stimulus: "",
      question: "A spinner has 8 equal sections numbered 1 through 8. What is the probability of landing on a prime number?",
      choices: { A: "1/2", B: "3/8", C: "5/8", D: "3/4" },
      correct_answer: "A",
      explanation: "Prime numbers from 1 to 8: 2, 3, 5, 7. That is 4 out of 8 sections, so P = 4/8 = 1/2."
    },
    {
      id: "qt_q9",
      type: "multiple_choice",
      domain: "Algebra",
      difficulty: "hard",
      stimulus: "",
      question: "If f(x) = 2x - 1 and g(x) = x² + 3, what is g(f(2))?",
      choices: { A: "9", B: "10", C: "12", D: "19" },
      correct_answer: "C",
      explanation: "f(2) = 2(2) - 1 = 3. g(3) = 9 + 3 = 12."
    },
    {
      id: "qt_q10",
      type: "multiple_choice",
      domain: "Advanced Math",
      difficulty: "hard",
      stimulus: "",
      question: "If (x + 2)(x - 5) = x² + kx - 10, what is the value of k?",
      choices: { A: "-3", B: "2", C: "5", D: "-10" },
      correct_answer: "A",
      explanation: "(x + 2)(x - 5) = x² - 5x + 2x - 10 = x² - 3x - 10, so k = -3."
    }
  ]
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = SAT_QUESTIONS;
}
